# HW 1

In [10]:
import torch
from torch.autograd import Variable

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

# X вручную
x = torch.FloatTensor([[[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]], 
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]],
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]]])

# y через randn
y = torch.randn(3, 4, 5)

# Проверка
x, y

(tensor([[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]]]),
 tensor([[[-2.5810,  0.9975,  1.2500,  2.0545,  0.2039],
          [ 0.4351, -0.0522, -1.6476,  2.5855,  0.4794],
          [ 0.1651, -1.6357, -1.4228,  0.5052, -2.2488],
          [-0.5849,  0.1141,  0.0397, -0.7018, -1.4764]],
 
         [[ 1.1420, -1.5193, -0.3819, -0.1860, -2.5994],
          [-1.2136,  0.6138,  1.1191,  0.4757,  0.3974],
          [-1.2632,  0.1561, -0.4139, -1.4023, -0.8138],
          [ 1.1906, -0.4224, -1.3979,  1.0930, -1.3070]],
 
         [[ 0.7758,  1.2049, -0.5016,  1.0889,  1.1607],
          [ 1.0536,  0.6331, -0.1842, -0.6310, -2.0004],
          [-0.1381,  0.7110,  0

In [4]:
# 2. Выведите его форму (shape)

print('x:', x.type(), x.shape)
print('y:', y.type(), y.shape)

x: torch.FloatTensor torch.Size([3, 4, 5])
y: torch.FloatTensor torch.Size([3, 4, 5])


In [5]:
# 3. Приведите его к форме 6х10

x = torch.reshape(x, [6, 10])

# Проверка
x, x.shape

(tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.]]), torch.Size([6, 10]))

In [6]:
# 4. Создайте случайный IntTensor размера 10

a = torch.IntTensor(10)

# Проверка
a.type(), a

('torch.IntTensor',
 tensor([ 102642176,          0,         24,          0,         -1,   16843009,
         1668444020, 1767059048, 1529374074,  824192054], dtype=torch.int32))

In [7]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

x * a

tensor([[ 1.0264e+08,  0.0000e+00,  2.4000e+01,  0.0000e+00, -1.0000e+00,
          3.3686e+07,  3.3369e+09,  3.5341e+09,  3.0587e+09,  1.6484e+09],
        [ 3.0793e+08,  0.0000e+00,  7.2000e+01,  0.0000e+00, -3.0000e+00,
          6.7372e+07,  6.6738e+09,  7.0682e+09,  6.1175e+09,  3.2968e+09],
        [ 1.0264e+08,  0.0000e+00,  2.4000e+01,  0.0000e+00, -1.0000e+00,
          3.3686e+07,  3.3369e+09,  3.5341e+09,  3.0587e+09,  1.6484e+09],
        [ 3.0793e+08,  0.0000e+00,  7.2000e+01,  0.0000e+00, -3.0000e+00,
          6.7372e+07,  6.6738e+09,  7.0682e+09,  6.1175e+09,  3.2968e+09],
        [ 1.0264e+08,  0.0000e+00,  2.4000e+01,  0.0000e+00, -1.0000e+00,
          3.3686e+07,  3.3369e+09,  3.5341e+09,  3.0587e+09,  1.6484e+09],
        [ 3.0793e+08,  0.0000e+00,  7.2000e+01,  0.0000e+00, -3.0000e+00,
          6.7372e+07,  6.6738e+09,  7.0682e+09,  6.1175e+09,  3.2968e+09]])

In [8]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

x @ x.T

tensor([[ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.]])

In [11]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = Variable(torch.Tensor([1]), requires_grad = True) # переменная является обучаемой
z = Variable(torch.Tensor([0.5]), requires_grad = True) # переменная является обучаемой
t = Variable(torch.Tensor([2]), requires_grad = True) # переменная является обучаемой

y = x**3 + z - 75*t

# Проверка
print('Значение функции y в точке:', y.item())

y.backward() # производная по всем переменным

# Проверка
print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) # частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [12]:
# 8. Создайте единичный тензор размера 5x6

e = torch.ones([5, 6])

# Проверка
e, e.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [13]:
# 9. Переведите его в формат numpy

e = e.numpy()

# Проверка
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)